name: .NET Build

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      solution_name: Orleans.Streams.Kafka-build.sln
      # Test_Project_Path: your-test-project-path

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Print Versions
      run: |
        dotnet --version
        dotnet --info
        echo Node Version:
        node -v

    - name: Extract Version
      run: |
        app_version=$(node -p "require('./package.json').version") >> $app_version

    # Execute all unit tests in the solution
#     - name: Execute unit tests
#       run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore ./"$solution_name" /p:Configuration="$Configuration"
      env:
        Configuration: ${{ matrix.configuration }}

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: | 
        dotnet pack "$solution_name" /p:PackageVersion=$app_version -c release
        dotnet nuget push ./*.nupkg -k $env:NUGET -s "nuget.org"
